config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'pages#home'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'friends', to: 'users#friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_key],
                                  endpoint: 'https://sandbox.iexapis.com/v1')
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
    
  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq 
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
    
  def self.matches(field_name, param)
      where("#{field_name} like ?", "%#{param}%")
  end
  
  def not_friends_with?(id)
    !self.friends.where(id: id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
    
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
       flash[:notice] = "Started following"
    else
      flash[:notice] = "Something went wrong"
    end
    redirect_to friends_path
  end

  def destroy
      friendship = current_user.friendships.where(friend_id: params[:id]).first
        friendship.destroy
        flash[:notice] = "Stopped following"
        redirect_to friends_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        
    end
    
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    
    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                render 'users/my_portfolio'
            else
                flash[:alert] = "Please enter a valid symbol"
                redirect_to my_portfolio_path
            end
        else
            flash[:alert] = "Please enter a search symbol"
            redirect_to my_portfolio_path
        end
    end
    
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
          stock = Stock.new_lookup(params[:ticker])
          stock.save
        end  
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end

    
    def index
        @stocks = Stock.all
    end
    
     def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
        redirect_to my_portfolio_path
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end
  
  def friends
    @cfriends = current_user.friends
  end
  
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friend = params[:friend]
      @cfriends = current_user.friends
      if @friends
          render 'users/friends'
      else
          flash[:alert] = "Couldn't find user"
          redirect_to friends_path
      end
    else
        flash[:alert] = "Please enter a search"
        redirect_to friends_path
    end
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-10">  
    <table class="table table-dark table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @cfriends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td>
                <%= link_to 'View Profile', user_path(friend),
                                             class: 'btn btn-sm btn-success' %>
                
                <%= button_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},
                                              class: 'btn btn-sm btn-warning mt-2' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success mt-3 alert-dismissible fade show' role="alert">
		<%= notice %>
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger mt-3 alert-dismissible fade show'>
		<%= alert %>
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
            </li>
            <% if current_user && current_user.friends.any? %>
              <li class="nav-item <%= 'active' if request.path == friends_path %>">
                          <%= link_to 'My Friends', friends_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profile
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                   <%= fa_icon 'edit' %> Edit profile
                  <% end %>
                </li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            
          </ul>
          <ul class='navbar-nav ml-auto m-2'>
            <li class="nav-item name">
              <% if current_user && current_user.first_name? %>
              <%= fa_icon 'user-circle-o' %> <%= "#{current_user.first_name} #{current_user.last_name}" %>
              <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
            </li>
              <% elsif current_user%>
              <%= fa_icon 'user-circle-o' %> <%= "Anonymous" %>
              
            </li>
           <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
            </li>
            <% end %>
            </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

  <head>
    <title>FinanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Finance App Home Page</h1>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/stocks/_list.html.erb
<table class="table table-dark table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
            <% @tracked_stocks.each do |stock| %>
                <tr>
                  <th scope="row" style="text-transform:uppercase"> <%= stock.ticker %> </th>
                  <td> <%= stock.name %> </td>
                  <td> <%= stock.last_price %> </td>
                  <td><% if !current_user.stock_already_tracked?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                                    class: "btn btn-xs btn-success", method: :post %>
                <% elsif current_user.id != @user.id %>
                  <span class="badge badge-secondary">
                    You are already tracking this stock
                  </span>
                <% end %>
              <% if current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                                          class: 'btn btn-sm btn-warning' %>
              <% end %>
            </td>
                </tr>
            <% end %>
      </tbody>
    </table>

app/views/user_stocks/index.html.erb
<h1>My portfolio</h1>

<div class="search-area col"> 
    <h2>Search stocks</h2>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row" >
            <div class="col sm-4 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Ticker symbol", autofocus: true,
                class:"form-control form-control-large" %>
            </div>
            <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 1x' %>
                    <% end %>
            </div>
        </div>
    <% end %>
</div>

<%= render 'users/result' %>


    <%= render 'stocks/list' %>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
      <table class="col">
          <tbody>
      
      <% @friends.each do |friend| %>
      <% if !(friend.email == current_user.email) %>
      <tr>
        <td><strong> Name: </strong> <%= friend.first_name %> <%= " " %> <%= friend.last_name %></td>
        <td><strong> Email: </strong> <%= friend.email %></td>
       <td> <%= link_to 'View Profile', user_path(friend),
                                             class: 'btn btn-sm btn-success' %> </td>
        <% if current_user.not_friends_with?(friend.id) %>
        <td> <%= button_to 'Follow', friendships_path(friend: friend), class: "btn btn-sm btn-success", method: :post %></td>
          <% else %>
              <td><strong> Already following </strong></td>
          <% end %>
      </tr>
      <% end %>
      
      <% end %>
      </tbody>
      </table>
  </div>
<% end %> 

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>' 

app/views/users/_result.html.erb
<% if @stock %>
 <div class="card">
    <div class="card card-header results-block">
        <strong>Symbol: </strong> <%= @stock.ticker %>
        <strong>Name: </strong> <%= @stock.name %>
        <strong>Price: </strong> <%= @stock.last_price %>
        
        <% if !current_user.stock_already_tracked?(@stock.ticker) %>
        <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", method: :post %>
        <% end %>
    </div>
 </div>
  
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/friends.html.erb
<h1>Friends</h1>

<div class='search-area col-10'>
  <h2>Search Friends</h2>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results">

</div>

<%= render 'users/friend_result' %>

<% if !@cfriends.empty? %>
  <%= render 'friends/list' %>
<% end %> 

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<div class="search-area col-10"> 
    <h2>Search stocks</h2>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row" >
            <div class="col-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Ticker symbol", autofocus: true,
                class:"form-control form-control-large" %>
            </div>
            <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 1x' %>
                    <% end %>
            </div>
        </div>
    <% end %>
</div>

<%= render 'users/result' %>

<% if @tracked_stocks %>
<div class="col col-10"> 
  <%= render 'stocks/list'%>
  </div>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.first_name %> <%= " " %> <%= @user.last_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= button_to 'Follow', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            
            <strong> You are friends </strong>
            
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>